
platform :ios, '7.0'

pod 'UMengSocial', '~> 4.3'

pod 'AFNetworking', '~> 2.5.0'

pod 'Masonry', '~> 0.5.3'

pod 'SDWebImage', '~> 5.7.1'

pod 'MBProgressHUD', '~> 0.9'

pod 'JSONModel', '~> 1.0.1'

pod 'UIAlertView-Blocks', '~> 1.0'

pod 'RegexKitLite', '~> 4.0'

pod 'OpenUDID', '~> 1.0.0'

pod 'FMDB', '~> 2.4'